language: node_js
node_js:
  - 10

cache: npm

stages:
  - compile
  - test
  - deploy-docs

before_install:
  - npm i -g lerna gh-pages

jobs:
  include:
  - stage: compile

    script: npm run build
  - stage: test
    script: npm run build && npm test